---
- name: Proceso de Failover Automático
  hosts: router1
  gather_facts: no
  tasks:
    - name: Cambiar ruta hacia el enlace de respaldo
      cisco.ios.ios_config:
        lines:
          # Elimina ruta principal (asumiendo IP 10.0.1.2)
          - no ip route 0.0.0.0 0.0.0.0 10.0.1.2 
          # Añade ruta respaldo (asumiendo IP 10.0.2.2)
          - ip route 0.0.0.0 0.0.0.0 10.0.2.2