[router1]
10.50.0.100 ansible_user=admin ansible_password=cisco ansible_network_os=ios ansible_connection=network_cli ansible_ssh_common_args='-c aes256-cbc -o KexAlgorithms=+diffie-hellman-group14-sha1 -o HostKeyAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no'

[router1:vars]
primary_gateway=10.0.1.2
backup_gateway=10.0.2.2
